version: '3'
services:
  db:
    image: mysql:8.0
    # mysql 8.0から必要になった
    command: --default-authentication-plugin=mysql_native_password
    #コンテナー削除してもmysqlのデータを引き継げる
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    # environment:
    #   RAILS_ENV: development
    depends_on:
      - db